---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-zwave-js-ui
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-mosquitto
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/apps/home/zwave-js-ui/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
