---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: brigman-home-assistant
  namespace: brigman
spec:
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.1
            envFrom: &envFrom
              - secretRef:
                  name: brigman-home-assistant-secret
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.1.6@sha256:3ae078c549ba6a0d2c6f2921aab53e492cd688956da6a51867e999f87ed59d13
            env:
              TZ: ${TIMEZONE}
              HASS_UNIT_SYSTEM: imperial
              HASS_PURGE_KEEP_DAYS: 30
              HASS_EXTERNAL_URL: https://brigman-hass.${SECRET_DOMAIN}
              HASS_TRUSTED_PROXIES: ${CLUSTER_POD_IP_CIDR}
            envFrom: *envFrom
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 500m
                memory: 100M
                hugepages-2Mi: 500Mi
              limits:
                cpu: 2500m
                memory: 750M
                hugepages-2Mi: 500Mi
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.21.0@sha256:0628049353bcef00cb4c913f20b3498fcd72a00d78306e01317ae09071bedfb5
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
            workingDir: /config
            args:
              - --auth
              - none
              - --user-data-dir
              - /config/.vscode
              - --extensions-dir
              - /config/.vscode
              - --port
              - "12321"
            volumeMounts:
              - name: config
                mountPath: /config
    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 8123
      codeserver:
        type: ClusterIP
        controller: main
        ports:
          http:
            enabled: true
            port: 12321
            protocol: TCP
            targetPort: 12321
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          hajimari.io/icon: mdi:home-assistant
          nginx.org/websocket-services: home-assistant
        hosts:
          - host: &host brigman-hass.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
      codeserver:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.networking.svc.cluster.local/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: ${SECRET_AUTH_URL}
        hosts:
          - host: &host brigman-hass-code.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: codeserver
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: brigman-home-assistant-config
