---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-es
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Nextcloud
        POSTGRES_HOST: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.databases.svc.cluster.local/{{ .NEXTCLOUD_DB }}"
        POSTGRES_DB: "{{ .NEXTCLOUD_DB }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASS }}"
        NEXTCLOUD_ADMIN_USER: "{{ .NEXTCLOUD_USER }}"
        NEXTCLOUD_ADMIN_PASSWORD: "{{ .NEXTCLOUD_PASSWORD }}"
        # REDIS_HOST: "redis-master"
        SMTP_HOST: "smtp.gmail.com"
        SMTP_SECURE: "tls"
        SMTP_PORT: "587"
        SMTP_AUTHTYPE: "LOGIN"
        SMTP_NAME: "{{ .GMAIL_FROM_EMAIL }}"
        SMTP_PASSWORD: "{{ .GMAIL_FROM_EMAIL_PW }}"
        MAIL_FROM_ADDRESS: "{{ .GMAIL_FROM_EMAIL }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .NEXTCLOUD_DB }}"
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: cloudnative-pg
    - extract:
        key: gmail
