---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
  namespace: *app
spec:
  interval: 60m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        name: bjw-s-charts
        kind: HelmRepository
        namespace: flux-system
  values:
    controllers:
      main:
        replicas: 1
        initContainers:
          0-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.2
            envFrom: &envFrom
              - secretRef:
                  name: nextcloud-secret
          #1-occ-upgrade:
          #  image:
          #    repository: nextcloud
          #    tag: 28.0.0-apache
          #  command: ["/usr/bin/su"]
          #  args: ["www-data", "-s", "/bin/bash", "-c", "/usr/src/nextcloud/occ upgrade"]
          #  env:
          #    TZ: "${TIMEZONE}"
          #    OVERWRITEPROTOCOL: "https"
          #    OVERWRITEHOST: "nextcloud.${SECRET_DOMAIN}"
          #  envFrom: *envFrom
          #2-occ-app-upgrade:
          #  image:
          #    repository: nextcloud
          #    tag: 28.0.0-apache
          #  command: ["/usr/bin/su"]
          #  args: ["www-data", "-s", "/bin/bash", "-c", "/usr/src/nextcloud/occ app:update --all"]
          #  env:
          #    TZ: "${TIMEZONE}"
          #    OVERWRITEPROTOCOL: "https"
          #    OVERWRITEHOST: "nextcloud.${SECRET_DOMAIN}"
          #  envFrom: *envFrom
        containers:
          main:
            image: &ncimg
              repository: nextcloud
              tag: 29.0.0-apache
            env: &env
              TZ: ${TIMEZONE}
              # https://github.com/nextcloud/docker/issues/763
              # REDIS_HOST: "redis-master"
              NC_DOMAIN: &host nextcloud.${SECRET_DOMAIN}
              NEXTCLOUD_TRUSTED_DOMAINS: *host
              TRUSTED_PROXIES: '10.0.0.0/8'
            envFrom: *envFrom
            probes:
              startup:
                enabled: true
                type: TCP
                spec:
                  initialDelaySeconds: 5
                  timeoutSeconds: 1
                  periodSeconds: 1
                  failureThreshold: 7200 # 2 hours
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
                hugepages-2Mi: 250Mi
              limits:
                cpu: 4000m
                memory: 6000Mi
                hugepages-2Mi: 250Mi
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
        hosts:
          - host: &host nextcloud.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: nextcloud-cert
    persistence:
      config:
        enabled: true
        existingClaim: nextcloud-data
        globalMounts:
          - path: /var/www/html
