---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app nextcloud
  namespace: *app
spec:
  interval: 60m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        name: bjw-s-charts
        kind: HelmRepository
        namespace: flux-system
  values:
    controllers:
      main:
        replicas: 1
        initContainers:
          0-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.1
            envFrom: &envFrom
              - secretRef:
                  name: nextcloud-secret
          #1-occ-upgrade:
          #  image:
          #    repository: nextcloud
          #    tag: 28.0.0-apache
          #  command: ["/usr/bin/su"]
          #  args: ["www-data", "-s", "/bin/bash", "-c", "/usr/src/nextcloud/occ upgrade"]
          #  env:
          #    TZ: "${TIMEZONE}"
          #    OVERWRITEPROTOCOL: "https"
          #    OVERWRITEHOST: "nextcloud.${SECRET_DOMAIN}"
          #  envFrom: *envFrom
          #2-occ-app-upgrade:
          #  image:
          #    repository: nextcloud
          #    tag: 28.0.0-apache
          #  command: ["/usr/bin/su"]
          #  args: ["www-data", "-s", "/bin/bash", "-c", "/usr/src/nextcloud/occ app:update --all"]
          #  env:
          #    TZ: "${TIMEZONE}"
          #    OVERWRITEPROTOCOL: "https"
          #    OVERWRITEHOST: "nextcloud.${SECRET_DOMAIN}"
          #  envFrom: *envFrom
        containers:
          main:
            image: &ncimg
              repository: nextcloud
              tag: 28.0.0-apache
            env: &env
              TZ: ${TIMEZONE}
              # https://github.com/nextcloud/docker/issues/763
              # REDIS_HOST: "redis-master"
              NC_DOMAIN: &host nextcloud.${SECRET_DOMAIN}
              NEXTCLOUD_DATA_DIR: /data
              NEXTCLOUD_TRUSTED_DOMAINS: *host
              TRUSTED_PROXIES: '10.0.0.0/8'
            envFrom: *envFrom
            probes:
              startup:
                enabled: true
                type: TCP
                spec:
                  initialDelaySeconds: 5
                  timeoutSeconds: 1
                  periodSeconds: 1
                  failureThreshold: 7200 # 2 hours
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
                hugepages-2Mi: 250Mi
              limits:
                cpu: 4000m
                memory: 6000Mi
                hugepages-2Mi: 250Mi
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: "nginx-external"
        annotations:
          haproxy.org/backend-config-snippet: |
            acl url_discovery path /.well-known/caldav /.well-known/carddav
            http-request redirect location /remote.php/dav/ code 301 if url_discovery
            option http-keep-alive
            timeout server 120000ms
          haproxy.org/response-set-header: |
            Strict-Transport-Security "max-age=31536000"
            X-Frame-Options "SAMEORIGIN"
            X-Content-Type-Options "nosniff"
            X-Download-Options "NoOpen"
            Referrer-Policy "no-referrer-when-downgrade"
        hosts:
          - host: "nextcloud.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - secretName: "nextcloud-cert"
    persistence:
      config:
        enabled: true
        existingClaim: nextcloud-config
        mountPath: /var/www/html
      nextcloud-data:
        enabled: true
        existingClaim: nextcloud-data
        mountPath: /var/www/html/data
