---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    template:
      engineVersion: v2
      data:
        # App
        FRIGATE_MQTT_HOST: "{{ .MQTT_HOST }}"
        FRIGATE_MQTT_USER: "{{ .MQTT_USERNAME }}"
        FRIGATE_MQTT_PASSWORD: "{{ .MQTT_PASSWORD }}"
        PLUS_API_KEY: "{{ .PLUS_API_KEY }}"
  dataFrom:
    - extract:
        key: frigate
