---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./pvc.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: frigate-configmap
    namespace: home
    files:
      - ./configs/config.yml
  - name: frigate-gatus-ep
    files:
      - ./configs/gatus.yaml
    options:
      labels:
        gatus.io/enabled: "true"
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
