---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./pvc.yaml
  - ./helmrelease.yaml
  - ./volsync.yaml
configMapGenerator:
  - name: frigate-configmap
    namespace: home
    files:
      - config.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled