---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-data
  namespace: home
  labels:
    app.kubernetes.io/name: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
  storageClassName: ${CLUSTER_STORAGE_NFS}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  namespace: home
  labels:
    app.kubernetes.io/name: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Ti
  storageClassName: ${CLUSTER_STORAGE_NFS}
