apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-adminstxt
    namespace: gaming
data:
    Admins.txt: ENC[AES256_GCM,data:yMpZWK8bIbuqi94SQJ0wyEA=,iv:jHclOitezl3gkWdPriwoq3A3ahzOVGh1qjDyqe0ZbEQ=,tag:R989YGaqQbcrnSuYFWutUg==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS3d5Q3VCdytLRmFjYmlk
            TEZHQ2lTek5uTkw0aFRJdHpoYldaL1gxWEVBClhHcDNTNkpJWWIzSHNWcWgwcVoz
            RFJXbDVJS0RlT25sa0QxMEpnL20zekEKLS0tIHNsMVdXQ1FBalQ0SVBSTytZdE1n
            L09vcmo5T0txMWo5dnNJekI2Q0hxaXMKKPknC8UkTijKcc8Vx79+svB94vHi5S7C
            qlaCfjrLysLTTbGbyBohngoDTVWPjiHownrJ1hSqv/RkUwsVX0G+fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T06:03:14Z"
    mac: ENC[AES256_GCM,data:v9jZnWsJyW+XIwBzlaflqPsgEdgSS/MZh7NQ+Kh8FMCbnD0OJi16t/XxyTnD4TJxcDSDx2YKxvJX803smEIwpmDqR9SrWv47ZfF6DEgy6/nn44ZUIs69lcu/ajvJhox2tL1q041yzrzQfCW20lKnKpFQ4xiYrfXvoFEEsfTA+TU=,iv:rNBQ87s/jT7Rmb6MgJ00sGaLczZhKe/babk0Sz8Bpws=,tag:SLmGOsOHRj5Hy13wtfjHvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-gameusersettingsini
    namespace: gaming
stringData:
    GameUserSettings.ini: ENC[AES256_GCM,data:ldmneDBcAQ82S9sUznOlXou+xD1YZ2ZP+i0IyrXzFvRYyUSrbleqP5guJfccQdiX2nxuyGL8rmy5uV99ucL4KpFDal0GCgGQ/hOLSMbdy88Y/vxN2jtqo7j0QCKLlSIWMwayFMnwYkGqZNxO+zdeHCVpM57rgVCnp3YiDHb94eN48togMSLSzoA+YuGlc5Ar0fCD/5Vh0HJo8J6J53xrJWbxXw==,iv:F0RL1IcGNlq/BWiwDH/TYAzABcPVztK1kw4z1e1jQKA=,tag:odKkWE1vmjex/lx89hHyzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS3d5Q3VCdytLRmFjYmlk
            TEZHQ2lTek5uTkw0aFRJdHpoYldaL1gxWEVBClhHcDNTNkpJWWIzSHNWcWgwcVoz
            RFJXbDVJS0RlT25sa0QxMEpnL20zekEKLS0tIHNsMVdXQ1FBalQ0SVBSTytZdE1n
            L09vcmo5T0txMWo5dnNJekI2Q0hxaXMKKPknC8UkTijKcc8Vx79+svB94vHi5S7C
            qlaCfjrLysLTTbGbyBohngoDTVWPjiHownrJ1hSqv/RkUwsVX0G+fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T06:03:14Z"
    mac: ENC[AES256_GCM,data:v9jZnWsJyW+XIwBzlaflqPsgEdgSS/MZh7NQ+Kh8FMCbnD0OJi16t/XxyTnD4TJxcDSDx2YKxvJX803smEIwpmDqR9SrWv47ZfF6DEgy6/nn44ZUIs69lcu/ajvJhox2tL1q041yzrzQfCW20lKnKpFQ4xiYrfXvoFEEsfTA+TU=,iv:rNBQ87s/jT7Rmb6MgJ00sGaLczZhKe/babk0Sz8Bpws=,tag:SLmGOsOHRj5Hy13wtfjHvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
