apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-adminstxt
    namespace: gaming
data:
    Admins.txt: ENC[AES256_GCM,data:OJtaP9uFtNndBZfyH+rJOtw=,iv:zQZT+TknnUUcu7sR80IM1pI3YQ8agG/lrmmjbDqjce4=,tag:/HKGa6nC3NNOx2WZgDhxyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNnBIQjMyWWE2ait2K3Bo
            VlR1cVNhMVlGSXYzbzhtSUZXSW9jKzdqZEJnClJZQzZIVXJpRnkzc1VwSmEyRDZH
            b2preEcybk5ObzRBTDF6NEg4K0VneEkKLS0tIEZ1eklvM09ueUJlRDgrU1pyYnpE
            clV5endnMy8vS21yaEJZZE1CREZ4TFUKpn891HYRVLCECXJIWDT5HPbdyuyrfsJk
            lMVAmHNh65+RUomI5bq13YQS4a7v2Q8rY+Omzayjv2LzGQ/G6N+bbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T06:28:11Z"
    mac: ENC[AES256_GCM,data:G39X5BENo/KbQNDGkSfIG7OlSiJMftWIY1uIQHH9+LbjtnrHENMOAGl0ur96G1ErHnfwZqBtbyKTEyQfoZBVOYvUZtFMPKtvuF5mzsOKoHSR9FPJGH2AfRavWuqhqnPJ3EaCG8x3ijxbV8XPy3XxBPP0Wsy1WsT9DYQ+SHXIO1A=,iv:tGiwAZwyOyPen/yE+seioOFNLxiHqn/D5BGB2fXMJFo=,tag:q0fgLLo0U/Ec0Hzzl0rrrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-gameusersettingsini
    namespace: gaming
stringData:
    GameUserSettings.ini: ENC[AES256_GCM,data:ErL4OWQAxSyIbWZWA04O1X5qzkVmzUbkHBv9bWWTpDEAuqXhqmon9EYIvmDr4xwRbKWcRMxr4Wp8P5D333CpOjmpqmp7oxmoFMZOHXStI4CIZjF2kmMACcyfufCOnHHIm5zBKDNazq8bdpII5EFnrWa/ZwJqufFs3t1Borb+rCI5yIqlY8mSs+i7Wk1qNVIS/ycCdwvRBtxQ83T57hE06e+MnA==,iv:SHLuu8BBMA40O3rwoLdo+K2a4pcLBsFmMTfpg9jpQY8=,tag:hBVWri/61mdb9aRSWnLwHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNnBIQjMyWWE2ait2K3Bo
            VlR1cVNhMVlGSXYzbzhtSUZXSW9jKzdqZEJnClJZQzZIVXJpRnkzc1VwSmEyRDZH
            b2preEcybk5ObzRBTDF6NEg4K0VneEkKLS0tIEZ1eklvM09ueUJlRDgrU1pyYnpE
            clV5endnMy8vS21yaEJZZE1CREZ4TFUKpn891HYRVLCECXJIWDT5HPbdyuyrfsJk
            lMVAmHNh65+RUomI5bq13YQS4a7v2Q8rY+Omzayjv2LzGQ/G6N+bbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T06:28:11Z"
    mac: ENC[AES256_GCM,data:G39X5BENo/KbQNDGkSfIG7OlSiJMftWIY1uIQHH9+LbjtnrHENMOAGl0ur96G1ErHnfwZqBtbyKTEyQfoZBVOYvUZtFMPKtvuF5mzsOKoHSR9FPJGH2AfRavWuqhqnPJ3EaCG8x3ijxbV8XPy3XxBPP0Wsy1WsT9DYQ+SHXIO1A=,iv:tGiwAZwyOyPen/yE+seioOFNLxiHqn/D5BGB2fXMJFo=,tag:q0fgLLo0U/Ec0Hzzl0rrrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
