apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-adminstxt
    namespace: gaming
stringData:
    Admins.txt: ENC[AES256_GCM,data:G6fU9lSoL1pWvf40aAfvHmIm,iv:0pGHQrKEZXIxEomj+3F2poHtlG56jR4FsyLsBhwe1lE=,tag:Jm141PVLFv3EsI+YAtG0jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNnBIQjMyWWE2ait2K3Bo
            VlR1cVNhMVlGSXYzbzhtSUZXSW9jKzdqZEJnClJZQzZIVXJpRnkzc1VwSmEyRDZH
            b2preEcybk5ObzRBTDF6NEg4K0VneEkKLS0tIEZ1eklvM09ueUJlRDgrU1pyYnpE
            clV5endnMy8vS21yaEJZZE1CREZ4TFUKpn891HYRVLCECXJIWDT5HPbdyuyrfsJk
            lMVAmHNh65+RUomI5bq13YQS4a7v2Q8rY+Omzayjv2LzGQ/G6N+bbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T06:14:59Z"
    mac: ENC[AES256_GCM,data:+x2oOfeLuFdGy2vJlfnVN+yZYOzOjTOGm7xpNB03SD9ZEjBCHblzdM81Q+MSouZz4XPsifEYq/CY9X/9mKTwqafK0mcrGuZoDNMAnN0Maj6GIePZi4wLNtPjlscmPfg9if3F+Hv2aw6pAwkk+NUBVflcJ/5hlgcAtTYQylWsmEA=,iv:RuSyMuB9Hz8N63nEEWcv/O8c6ThG6iE+PSqNx2Fm1X4=,tag:fk1ZlQDMZRwrOePmnJ6J6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-gameusersettingsini
    namespace: gaming
stringData:
    GameUserSettings.ini: ENC[AES256_GCM,data:s/oNfukrG7N5S3jDX9I+02Q00B6PsXBlvv/x4gvpszi6F2J9SUNwpBuI+vHXCoxnGQ9TUJmn0gM0plNCvZXZz7lsSZfI6+l2dgNBiLMIzARO9NPskZQB88jJL79Q+Nih2OQz//tnzglm49vPHNKl7OeipBtwdAfF5de4a3HJqDDsY/q34Acu3zEr0aUSTuF2dY2rtXvzxmxpgYfGK64G+ZDTph3/xGq+EojE3aoayOAgL2hjuSw3yaCdIXOgvv/taeeqjEWTQ0Apdlu7Z3T92EAl1MxTokQQlvhdCVYja/LfcU6t6cK5w5CZhLz3PoftF2lb9/Zu8SEu/oP2+aJVtwxGVx/Zp538XDvuq8v7nqM=,iv:FG5bZLavbWqXqUnBQkimH92HKIl5Nys/ERVC5yEcvck=,tag:K+ehlcl8foN3H9nb7jd1bA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNnBIQjMyWWE2ait2K3Bo
            VlR1cVNhMVlGSXYzbzhtSUZXSW9jKzdqZEJnClJZQzZIVXJpRnkzc1VwSmEyRDZH
            b2preEcybk5ObzRBTDF6NEg4K0VneEkKLS0tIEZ1eklvM09ueUJlRDgrU1pyYnpE
            clV5endnMy8vS21yaEJZZE1CREZ4TFUKpn891HYRVLCECXJIWDT5HPbdyuyrfsJk
            lMVAmHNh65+RUomI5bq13YQS4a7v2Q8rY+Omzayjv2LzGQ/G6N+bbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T06:14:59Z"
    mac: ENC[AES256_GCM,data:+x2oOfeLuFdGy2vJlfnVN+yZYOzOjTOGm7xpNB03SD9ZEjBCHblzdM81Q+MSouZz4XPsifEYq/CY9X/9mKTwqafK0mcrGuZoDNMAnN0Maj6GIePZi4wLNtPjlscmPfg9if3F+Hv2aw6pAwkk+NUBVflcJ/5hlgcAtTYQylWsmEA=,iv:RuSyMuB9Hz8N63nEEWcv/O8c6ThG6iE+PSqNx2Fm1X4=,tag:fk1ZlQDMZRwrOePmnJ6J6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
