apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-adminstxt
    namespace: gaming
stringData:
    Admins.txt: ENC[AES256_GCM,data:G6fU9lSoL1pWvf40aAfvHmIm,iv:0pGHQrKEZXIxEomj+3F2poHtlG56jR4FsyLsBhwe1lE=,tag:Jm141PVLFv3EsI+YAtG0jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNnBIQjMyWWE2ait2K3Bo
            VlR1cVNhMVlGSXYzbzhtSUZXSW9jKzdqZEJnClJZQzZIVXJpRnkzc1VwSmEyRDZH
            b2preEcybk5ObzRBTDF6NEg4K0VneEkKLS0tIEZ1eklvM09ueUJlRDgrU1pyYnpE
            clV5endnMy8vS21yaEJZZE1CREZ4TFUKpn891HYRVLCECXJIWDT5HPbdyuyrfsJk
            lMVAmHNh65+RUomI5bq13YQS4a7v2Q8rY+Omzayjv2LzGQ/G6N+bbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T19:17:05Z"
    mac: ENC[AES256_GCM,data:qkgd3DaDnGwEkwWWstW0DAZ/2sZe9hJotl8Dsm23tgppaz1R5J3HI+1Gne2dUFj7ZChX+PisZVcR2IeVpgpXXIfAeddjRapG+adsdNozbGD1sQJv7Au+ytZ8IgdvZOQ50+5M/oqG1w+mmoHGkU00xD07kpQ5LdzvLbB2gwpIOrQ=,iv:5vPppSqgfFKuKy0vXMevyde7UouqXGhmWF27um6qnf4=,tag:28AOOhWLJTco+sJ8udKz9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: insurgency-sandstorm-gameusersettingsini
    namespace: gaming
stringData:
    GameUserSettings.ini: ENC[AES256_GCM,data:ErL4OWQAxSyIbWZWA04O1X5qzkVmzUbkHBv9bWWTpDEAuqXhqmon9EYIvmDr4xwRbKWcRMxr4Wp8P5D333CpOjmpqmp7oxmoFMZOHXStI4CIZjF2kmMACcyfufCOnHHIm5zBKDNazq8bdpII5EFnrWa/ZwJqufFs3t1Borb+rCI5yIqlY8mSs+i7Wk1qNVIS/ycCdwvRBtxQ83T57hE06e+MnA==,iv:SHLuu8BBMA40O3rwoLdo+K2a4pcLBsFmMTfpg9jpQY8=,tag:hBVWri/61mdb9aRSWnLwHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNnBIQjMyWWE2ait2K3Bo
            VlR1cVNhMVlGSXYzbzhtSUZXSW9jKzdqZEJnClJZQzZIVXJpRnkzc1VwSmEyRDZH
            b2preEcybk5ObzRBTDF6NEg4K0VneEkKLS0tIEZ1eklvM09ueUJlRDgrU1pyYnpE
            clV5endnMy8vS21yaEJZZE1CREZ4TFUKpn891HYRVLCECXJIWDT5HPbdyuyrfsJk
            lMVAmHNh65+RUomI5bq13YQS4a7v2Q8rY+Omzayjv2LzGQ/G6N+bbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T19:17:05Z"
    mac: ENC[AES256_GCM,data:qkgd3DaDnGwEkwWWstW0DAZ/2sZe9hJotl8Dsm23tgppaz1R5J3HI+1Gne2dUFj7ZChX+PisZVcR2IeVpgpXXIfAeddjRapG+adsdNozbGD1sQJv7Au+ytZ8IgdvZOQ50+5M/oqG1w+mmoHGkU00xD07kpQ5LdzvLbB2gwpIOrQ=,iv:5vPppSqgfFKuKy0vXMevyde7UouqXGhmWF27um6qnf4=,tag:28AOOhWLJTco+sJ8udKz9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
