---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: l3-policy
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - localASN: ${SECRET_NETWORK_BGP_ASN}
      exportPodCIDR: false
      serviceSelector:
        matchExpressions:
          - {
              key: thisFakeSelector,
              operator: NotIn,
              values: ["will-match-and-announce-all-services"],
            }
      neighbors:
        - peerAddress: ${CILIUM_BGP_PEER}/32
          peerASN: ${SECRET_NETWORK_BGP_PEER_ASN}
