---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-config
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-config-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: immich-config-tpl
            items:
              - key: immich.config.json