---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: immich-config-tpl
    files:
      - ./config/immich.config.json
generatorOptions:
  disableNameSuffixHash: true
labels:
  - pairs:
      app.kubernetes.io/name: immich-server
      app.kubernetes.io/instance: immich-server
      app.kubernetes.io/part-of: immich
