---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Home Assistant
        ELEVATION: "{{ .HASS_ELEVATION }}"
        LATITUDE: "{{ .HASS_LATITUDE }}"
        LONGITUDE: "{{ .HASS_LONGITUDE }}"
  dataFrom:
    - extract:
        key: home-assistant
