---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdaemon-config
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ${CLUSTER_STORAGE_BLOCK_SSD}
