---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdaemon-config
  namespace: home
  labels:
    app.kubernetes.io/name: appdaemon
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ${CLUSTER_STORAGE_NFS}
