---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: appdaemon-restic
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: appdaemon-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .REPOSITORY_TEMPLATE }}/appdaemon"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: appdaemon
  namespace: home
spec:
  sourcePVC: appdaemon-config
  trigger:
    schedule: "0 8 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: appdaemon-restic-secret
    cacheCapacity: 8Gi
    volumeSnapshotClassName: ${CLUSTER_SNAPSHOT_BLOCK_SSD}
    storageClassName: ${CLUSTER_STORAGE_BLOCK_SSD}
    cacheStorageClassName: ${CLUSTER_STORAGE_BLOCK_SSD}
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 10
      within: 3d
