---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx-external
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/ingress-nginx/external
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx-internal
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/ingress-nginx/internal
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
