---
apiVersion: v1
kind: Namespace
metadata:
  name: home
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
