---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gaming
resources:
  - config/secrets.sops.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: insurgency-sandstorm-gameini
    namespace: gaming
    files:
      - ./config/Game.ini
  - name: insurgency-sandstorm-engineini
    namespace: gaming
    files:
      - ./config/Engine.ini
  - name: insurgency-sandstorm-mapcycletxt
    namespace: gaming
    files:
      - ./config/MapCycle.txt
  - name: insurgency-sandstorm-modstxt
    namespace: gaming
    files:
      - ./config/Mods.txt
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
labels:
  - pairs:
      app.kubernetes.io/name: insurgency-sandstorm
      app.kubernetes.io/instance: insurgency-sandstorm
