---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-redis
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/immich/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-pvc-media
    - name: cluster-apps-external-secrets-stores
    - name: immich-redis
    - name: cluster-apps-cloudnative-pg-cluster
  path: ./kubernetes/apps/media/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
