---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clean-slate-factorio
  namespace: flux-system
spec:
  path: ./kubernetes/apps/gaming/factorio/clean-slate
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
