---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: factorio
  namespace: gaming
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: factorio-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        USERNAME: {{ .FACTORIO_USER }}
        TOKEN: {{ .FACTORIO_TOKEN }}
  dataFrom:
    - extract:
        key: factorio
