---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zwave-js-ui
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: zwavejs/zwave-js-ui
              tag: 9.6.2
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                smarter-devices/serial_by-id_usb-0658_0200-if00: 1
                cpu: 10m
                memory: 100M
              limits:
                smarter-devices/serial_by-id_usb-0658_0200-if00: 1
                memory: 256M
        pod:
          nodeSelector:
            aeotec.feature.node.kubernetes.io/zwave: "true"
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:zwave
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host zwave.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: zwave-js-ui-cert
    persistence:
      config:
        enabled: true
        existingClaim: zwave-js-ui-config
        globalMounts:
          - path: /usr/src/app/store
    service:
      main:
        ports:
          http:
            port: 8091
    resources:
      requests:
        smarter-devices/ttyACM0: 1
        cpu: 10m
        memory: 100M
      limits:
        smarter-devices/ttyACM0: 1
        memory: 256M
