---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-js-ui-config
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ${CLUSTER_STORAGE_NFS}
