---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: videos
  namespace: media
spec:
  storageClassName: ''
  volumeName: videos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: music
  namespace: media
spec:
  storageClassName: ''
  volumeName: music
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-nfs
  namespace: media
spec:
  storageClassName: ''
  volumeName: immich-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Ti
