---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: videos
spec:
  storageClassName: ''
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: ${SECRET_FILESERV_VIDEOS_PATH}
    server: ${SECRET_FILESERV_IP}
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music
spec:
  storageClassName: ''
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: ${SECRET_FILESERV_MUSIC_PATH}
    server: ${SECRET_FILESERV_IP}
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs
spec:
  storageClassName: ''
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: ${SECRET_FILESERV_IMMICH_PATH}
    server: ${SECRET_FILESERV_IP}
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
