---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.30.0.6486-629d58034@sha256:b3e3a2a305443f243643553161cff639f3dcc74349595884ac9c77cf6bb24068
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 1000m
                memory: 2000M
              limits:
                gpu.intel.com/i915: 1
                memory: 10000M
        pod:
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 44    # video
              - 109   # render
              - 65537 # media ro
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          hajimari.io/icon: mdi:plex
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host plex.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: plex-config
      tmp:
        type: emptyDir
      transcode:
        type: emptyDir
      movies:
        existingClaim: movies
      tv:
        existingClaim: tv
    service:
      main:
        ports:
          http:
            port: 32400
