---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media
  labels:
    app.kubernetes.io/name: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: ${CLUSTER_STORAGE_BLOCK_SSD}
