---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-longhorn
  namespace: flux-system
spec:
  targetNamespace: storage
  path: ./kubernetes/apps/storage/longhorn-system/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
