---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-appdaemon
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-home-assistant
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/apps/home/appdaemon/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
