---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-2024
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ${CLUSTER_STORAGE_NFS}
