---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gate
spec:
  storageClassName: ''
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: ${SECRET_FILESERV_GATE_PATH}
    server: ${SECRET_FILESERV_IP}
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  storageClassName: ''
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: ${SECRET_FILESERV_GATE_MYSQL_PATH}
    server: ${SECRET_FILESERV_IP}
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: security-camera
spec:
  storageClassName: ''
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: ${SECRET_FILESERV_SECURITY_CAMERA_PATH}
    server: ${SECRET_FILESERV_IP}
  mountOptions:
    - nfsvers=4.1
    - nconnect=8
    - hard
    - noatime
    - rsize=131072
    - wsize=131072