---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: kubelet-csr-approver
    repo: https://postfinance.github.io/kubelet-csr-approver
    version: 1.0.5
    releaseName: kubelet-csr-approver
    namespace: kube-system
    valuesInline:
      providerRegex: ^(dogbert|catbert|wally|alice|phil|work-pc|nuc0|nuc1|nuc2|thing1|thing2)$
      bypassDnsResolution: true
commonAnnotations:
  meta.helm.sh/release-name: kubelet-csr-approver
  meta.helm.sh/release-namespace: kube-system
commonLabels:
  app.kubernetes.io/managed-by: Helm