---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: databases
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0-10
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  env:
  - name: TZ
    value: ${TIMEZONE}
  storage:
    size: 50Gi
    storageClass: ${CLUSTER_STORAGE_NFS}
  superuserSecret:
    name: cloudnative-pg-secret
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
      hugepages-2Mi: 500Mi
    limits:
      memory: 2Gi
      hugepages-2Mi: 500Mi
