---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: databases
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.0-10
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  storage:
    size: 25Gi
    storageClass: ${CLUSTER_STORAGE_BLOCK_SSD}
  superuserSecret:
    name: cloudnative-pg-secret
  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 500m
      memory: 500M
      hugepages-2Mi: 500Mi
    limits:
      memory: 2Gi
      hugepages-2Mi: 500Mi
