---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./blackbox-exporter/ks.yaml
  - ./radarr-exporter/ks.yaml
  - ./sabnzbd-exporter/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./sonarr-exporter/ks.yaml
  - ./speedtest-exporter/ks.yaml
