---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-plex
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-volsync
    - name: cluster-apps-pvc-media
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/apps/media/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
